### PR TITLE
Review PR

### PR DESCRIPTION
**Pull request by Ahmed-Benj**
Hello TSE,

Could you please review our project?

And indicate details if there is something to be fixed/adjusted ?

Kind regards,
Ahmed

### CODE REVIEW

**Comment by BrittanyBlake** [comment]
### Pull request under review by Brittany Blake (TSE)

**Review by BrittanyBlake — CHANGES_REQUESTED** [review]
### Status: Changes Required ♻️ 
****
### Hi @Ahmed-Benj  and @john4pius! 👋 👋 
You have done a great job with your project so far!👍 It looks really close to the original page! 👏 👏 👏  There are just a few issues that need to be resolved before you can move on: ⬇️ 
****

- [ ] The HTML validator is still showing an error. 👇 
Screen Shot 2020-06-11 at 1 52 10 AM

- Please use [this website](https://validator.w3.org) to check your code and fix the errors/warnings.

- [ ] The lock icon in your password input box is not properly positioned. Please compare it with the original page and fix this.
Your clone 👇 
Screen Shot 2020-06-11 at 1 53 39 AM
The original page 👇 
Screen Shot 2020-06-11 at 1 53 19 AM
- [ ] The text in the "create account" and "sign in" buttons are not positioned correctly. It should be in the middle of the button. Please compare it with the original page and correct this.
Your clone 👇 
Screen Shot 2020-06-11 at 1 53 32 AM
The original page 👇 
Screen Shot 2020-06-11 at 1 53 25 AM
Your clone 👇 
Screen Shot 2020-06-11 at 1 53 53 AM
The orignal page 👇 
Screen Shot 2020-06-11 at 1 53 59 AM

- [ ] There should be more space between the bottom of the form and the footer. Please compare it with the original page and fix this.
Your clone 👇 
Screen Shot 2020-06-11 at 1 54 27 AM
The original page 👇 
Screen Shot 2020-06-11 at 1 54 34 AM







****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Comment by tirthajyoti-ghosh** [comment]
# Pull Request under review by T. Ghosh (TSE)

**Review by tirthajyoti-ghosh — APPROVED** [review]
# Status: Approved ✔

## Congratulations @Ahmed-Benj and @john4pius  🎉

### Thanks for implementing the changes. It's a 👍 from me. Go ahead and merge it. Good luck with your next projects.

Happy coding 👨‍💻

**Pull request merged**
